# Generated by Django 6.0.4 on 2026-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_clerk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clerk_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
    ]
