# Generated by Django 6.0.4 on 2026-05-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaldoctor_historicalnurse_historicalpatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnurse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpatient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalstaff',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDoctor',
        ),
        migrations.DeleteModel(
            name='HistoricalNurse',
        ),
        migrations.DeleteModel(
            name='HistoricalPatient',
        ),
        migrations.DeleteModel(
            name='HistoricalStaff',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
