# Generated by Django 6.0.4 on 2026-05-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_labreport_delete_lapreport'),
        ('users', '0004_remove_user_clerk_id_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='pulse',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('READY', 'Ready')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='users.nurse'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='temperature',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitals',
            name='weight',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient', 'scheduled_at')},
        ),
    ]
