# Generated by Django 6.0.4 on 2026-05-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vitals_pulse_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
