# Generated by Django 6.0.4 on 2026-05-08 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medication',
            new_name='medicines',
        ),
        migrations.AddField(
            model_name='vitals',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
