# Generated by Django 6.0.4 on 2026-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Prescription', 'Prescription'), ('LabReport', 'Lab Report')], default='APPOINTMENT', max_length=20),
            preserve_default=False,
        ),
    ]
