# Generated by Django 6.0.4 on 2026-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
